server:
  port: 8080

spring:
  application:
    name: ecommerce-service

#  data:
#    mongodb:
#      uri: mongodb+srv://praveen369soni:WuVutv9qSVSV6DI4@cluster0.jumqikj.mongodb.net/ecommerce?retryWrites=true&w=majority&appName=Cluster0
#      database: ecommerce

  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: mongo-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
