server:
  port: 8080

spring:
  application:
    name: ecommerce-service

  data:
    mongodb:
      uri: mongodb+srv://praveen369soni:WuVutv9qSVSV6DI4@cluster0.jumqikj.mongodb.net/ecommerce?retryWrites=true&w=majority&appName=Cluster0
      database: ecommerce

  cache:
    type: hazelcast
  hazelcast:
    config: classpath:hazelcast.xml

hazelcast:
  network:
    rest-api:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.syscho.mongo: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
